package cn.ykccchen.script.exception;

/** Stable machine-readable categories for parse, compile and runtime failures. */
public enum ScriptErrorCode {
	SCRIPT_PARSE_ERROR,
	SCRIPT_COMPILE_ERROR,
	SCRIPT_TOKEN_ERROR,
	SCRIPT_RUNTIME_ERROR,
	SCRIPT_RESOURCE_NOT_FOUND,
	SCRIPT_SECURITY_ERROR,
	SCRIPT_NULL_ACCESS,
	SCRIPT_OPERATOR_ERROR,
	SCRIPT_TYPE_CONVERSION_ERROR,
	SCRIPT_UNSUPPORTED_OPERATION,
	SCRIPT_ASSIGNMENT_ERROR,
	SCRIPT_METHOD_RESOLUTION_ERROR,
	SCRIPT_ASYNC_ERROR,
	SCRIPT_ASYNC_REJECTED,
	SCRIPT_CANCELLED,
	SCRIPT_TIMED_OUT,
	SCRIPT_CHECKPOINT_LIMIT,
	SCRIPT_HOST_CALL_LIMIT
}
